### ISSUE TITLE
Improve UI for executing proposals

### ISSUE THREAD

**Issue by sembrestels** [1Hive/conviction-voting-app#11]
When the conviction on a proposal has passed the threshold, we still need to enact it. There are no mockups on figma for that case. For the moment, I added the "Enact proposal" button behind the proposal status.

This is how it is right now:
![Screenshot from 2019-09-17 19-16-09](https://user-images.githubusercontent.com/931684/65064111-02f28400-d980-11e9-916d-47dfc839a84a.png)

**Comment by lkngtn** [comment]
I'm not sure I like the use of "Has passed" here since its not really a definite state, it currently is passed the threshold that allows it to be executed, but it may not be in the future. 

For example we could have a situation where funds are added to the vault, which lowers the threshold on many proposals making them all eligible to be executed, after executing the first one there is less funds available and the other proposals are no longer at threshold. 

I think the status should be something like "Can be executed", and the call to action on the button should probably be "Execute proposal". 

I don't think enact is the right word as it typically refers to "making something into law" which doesn't quite fit the action of transferring funds. (I know this is what is used in the current voting app, but I think it ought to not be used their either... 🙈)

**Comment by sembrestels** [comment]
@jayalaves Worked in that issue too and has been implemented:

![Screenshot from 2020-03-01 14-09-58.png](https://images.zenhubusercontent.com/5e4308ceb45c3a9003f4f594/e57ae3ed-9697-4c09-a524-bacff70e0249)
