### ISSUE TITLE
Do we want to show the conviction graph?

### ISSUE THREAD

**Issue by sembrestels** [1Hive/conviction-voting-app#23]
I've been working on an improved version of the conviction chart. Now it shows the convictions (yours and total) for the last 50 units of time, and the prediction of those convictions for the next 50 units of time (in colored dashed lines). It also shows the threshold as an horizontal grey dashed line. Finally a vertical grey line separate the past and the future:

![Screenshot from 2019-10-05 16-23-38](https://user-images.githubusercontent.com/931684/66256305-c77ff400-e78c-11e9-8381-8eb7551e258e.png)

I think it's very useful to understand what is going on with the conviction of a proposal, but I'm afraid it is not easy to understand, so it might impact the UX.

What do you think? Do we show it or hide it? If we finally show it, do you have any feedback on how to improve it visually?

**Comment by lkngtn** [comment]
I have found the graph to be quite useful in explaining what is happening, but agree that without context it could seem quite unintuitive and complex.

**Comment by rperez89** [comment]
Hey @sembrestels @lkngtn want to bring this topic up again since i have the feeling that the graph is not working as expected.
So testing from your last commit @sembrestels  i have this behaviour
<img width="1675" alt="Screen Shot 2020-06-16 at 5 49 37 PM" src="https://user-images.githubusercontent.com/11763623/84826821-e8763580-aff9-11ea-920b-6f71fc74a958.png">

i not sure if i understand what is this graph for, is always being loaded with the same number from the position 25 of the array. So would really appreciate some input from you guys if this is needed or what is expected from this graph

**Comment by fabriziovigevani** [comment]
> is always being loaded with the same number from the position 25 of the array.

I guess this is because you just started supporting the proposal so it has no history from the previous 25 time units. As time passes, the graph should update accordingly showing the projection.

> And also think that is not providing us so much information maybe we want to just replace that graph for a CircleGraph component.

Not sure about this, the chart is meant to show you the conviction projection for all different stakes (as it's shown on the first image posted by David). Don't think that the CircleGraph serves the same purpose. It could be considered as replacement for the conviction progress bar which is more aligned with what is representing, but i think the bar is clear enough.

I think we should definitely add a label to the x axis (there are a couple more suggestions [here](https://github.com/1Hive/conviction-voting-app/issues/59))

**Comment by rperez89** [comment]
> I guess this is because you just started supporting the proposal so it has no history from the previous 25 time units. As time passes, the graph should update accordingly showing the projection.
> 
> >

Indeed remains in the same shape until the proposal is ready to be executed..., there is no change, not sure if it's an error or what.
But which is the meaning about having a conviction projection of more time than the proposal duration? why is that? in my mind what you need to know as an user is how far we are to get the proposal to be approved or not, the way that the graph is now we don't have any info

**Comment by GriffGreen** [comment]
A nice CV mockup: https://commons.invisionapp.com/console/Conviction-Voting-Prototype-ck0khwxhk02hd01d23mgl75rg/ck0khwyqe0myb01c7f6rnsv06/play
